"""Добавление поля success

Revision ID: 6eb50208b3d4
Revises: e63e0f08e6cf
Create Date: 2025-12-04 14:18:12.705129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6eb50208b3d4"
down_revision: Union[str, Sequence[str], None] = "e63e0f08e6cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применить миграцию (обновление схемы)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("habits", sa.Column("success", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатить миграцию (восстановление предыдущей схемы)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("habits", "success")
    # ### end Alembic commands ###
