"""Изменение поля success


Revision ID: 99ef640b294d
Revises: e65ea5fe7110
Create Date: 2025-12-12 15:22:55.530173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99ef640b294d"
down_revision: Union[str, Sequence[str], None] = "e65ea5fe7110"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применить миграцию (обновление схемы)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_checkins_habit_date", "habit_checkins", ["habit_id", "date"], unique=False
    )
    op.create_index("ix_habits_is_active", "habits", ["is_active"], unique=False)
    op.drop_column("habits", "success")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатить миграцию (восстановление предыдущей схемы)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("habits", sa.Column("success", sa.BOOLEAN(), nullable=False))
    op.drop_index("ix_habits_is_active", table_name="habits")
    op.drop_index("ix_checkins_habit_date", table_name="habit_checkins")
    # ### end Alembic commands ###
