"""Добавление поля complete_today

Revision ID: e63e0f08e6cf
Revises: ff6684c2bc76
Create Date: 2025-12-04 13:52:05.651000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e63e0f08e6cf"
down_revision: Union[str, Sequence[str], None] = "ff6684c2bc76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применить миграцию (обновление схемы)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("habits", sa.Column("completed_today", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатить миграцию (восстановление предыдущей схемы)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("habits", "completed_today")
    # ### end Alembic commands ###
